spring:
  application:
    name: doc-resolving-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    time-zone: GMT+8
server:
  servlet:
    context-path: /doc-resolving
