spring:
  application:
    name: docresolving
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    time-zone: GMT+8
server:
  servlet:
    context-path: /docresolving
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true