eureka:
  instance:
    instance-id: ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})
    hostname: localhost
  client:
    service-url:
      defaultZone: http://192.168.0.112:8761/eureka/,http://192.168.0.112:8762/eureka/

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
  - 192.168.0.111:22122
  web-server-url: http://192.168.0.111/